<?xml version="1.0"?>
<!-- 
Differential Drive Robot URDF with Basicmicro Hardware Interface
================================================================
This URDF describes a standard differential drive robot with two driven wheels
and a caster wheel, integrated with the Basicmicro hardware interface.

Usage:
  xacro differential_drive_robot.urdf.xacro > robot.urdf

Parameters (can be overridden via xacro arguments):
  - port: Serial port (default: /dev/ttyACM0)
  - baud: Baud rate (default: 38400)
  - address: Controller address (default: 128)
  - wheel_radius: Wheel radius in meters (default: 0.1)
  - wheel_separation: Distance between wheels (default: 0.3)
  - encoder_counts_per_rev: Encoder resolution (default: 1000)
  - gear_ratio: Gear ratio (default: 1.0)
  - motion_strategy: Motion control strategy (default: speed_accel)
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="basicmicro_diff_drive_robot">

  <!-- Xacro arguments with defaults -->
  <xacro:arg name="port" default="/dev/ttyACM0"/>
  <xacro:arg name="baud" default="38400"/>
  <xacro:arg name="address" default="128"/>
  <xacro:arg name="wheel_radius" default="0.1"/>
  <xacro:arg name="wheel_separation" default="0.3"/>
  <xacro:arg name="encoder_counts_per_rev" default="1000"/>
  <xacro:arg name="gear_ratio" default="1.0"/>
  <xacro:arg name="motion_strategy" default="speed_accel"/>
  <xacro:arg name="default_acceleration" default="1000"/>
  <xacro:arg name="buffer_depth" default="4"/>
  <xacro:arg name="encoder_type" default="incremental"/>
  <xacro:arg name="auto_home_on_startup" default="false"/>
  <xacro:arg name="position_limits_enabled" default="false"/>

  <!-- Robot constants -->
  <xacro:property name="wheel_radius" value="$(arg wheel_radius)"/>
  <xacro:property name="wheel_separation" value="$(arg wheel_separation)"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.3"/>
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_mass" value="10.0"/>
  
  <xacro:property name="caster_radius" value="0.05"/>
  <xacro:property name="caster_mass" value="0.2"/>

  <!-- Materials -->
  <material name="blue">
    <color rgba="0.0 0.0 1.0 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>
  
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="${base_mass * (base_width*base_width + base_height*base_height) / 12}"
               iyy="${base_mass * (base_length*base_length + base_height*base_height) / 12}"
               izz="${base_mass * (base_length*base_length + base_width*base_width) / 12}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}"
               iyy="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}"
               izz="${wheel_mass * wheel_radius*wheel_radius / 2}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}"
               iyy="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}"
               izz="${wheel_mass * wheel_radius*wheel_radius / 2}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Caster Wheel -->
  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${caster_mass}"/>
      <inertia ixx="${2 * caster_mass * caster_radius*caster_radius / 5}"
               iyy="${2 * caster_mass * caster_radius*caster_radius / 5}"
               izz="${2 * caster_mass * caster_radius*caster_radius / 5}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Left Wheel Joint -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Right Wheel Joint -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Caster Wheel Joint -->
  <joint name="caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="${base_length/2 - caster_radius} 0 ${-base_height/2 - caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ros2_control Hardware Interface -->
  <ros2_control name="BasicmicroSystem" type="system">
    <hardware>
      <plugin>basicmicro_ros2/BasicmicroHardwareInterface</plugin>
      
      <!-- Hardware connection parameters -->
      <param name="port">$(arg port)</param>
      <param name="baud">$(arg baud)</param>
      <param name="address">$(arg address)</param>
      
      <!-- Robot physical parameters -->
      <param name="wheel_radius">$(arg wheel_radius)</param>
      <param name="wheel_separation">$(arg wheel_separation)</param>
      <param name="encoder_counts_per_rev">$(arg encoder_counts_per_rev)</param>
      <param name="gear_ratio">$(arg gear_ratio)</param>
      
      <!-- Motion control parameters -->
      <param name="motion_strategy">$(arg motion_strategy)</param>
      <param name="buffer_depth">$(arg buffer_depth)</param>
      <param name="default_acceleration">$(arg default_acceleration)</param>
      
      <!-- Servo functionality parameters -->
      <param name="encoder_type">$(arg encoder_type)</param>
      <param name="auto_home_on_startup">$(arg auto_home_on_startup)</param>
      <param name="position_limits_enabled">$(arg position_limits_enabled)</param>
      <param name="min_position_left">-1000000</param>
      <param name="max_position_left">1000000</param>
      <param name="min_position_right">-1000000</param>
      <param name="max_position_right">1000000</param>
      <param name="limit_violation_behavior">soft_stop</param>
      <param name="limit_decel_rate">1000</param>
    </hardware>
    
    <!-- Left Wheel Interface -->
    <joint name="left_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    
    <!-- Right Wheel Interface -->
    <joint name="right_wheel_joint">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo Integration (optional) -->
  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
      <parameters>$(find basicmicro_ros2)/config/diff_drive_controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Gazebo wheel properties -->
  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
  </gazebo>
  
  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
  </gazebo>
  
  <gazebo reference="caster_wheel">
    <material>Gazebo/Grey</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>

</robot>