controller_manager:
  ros__parameters:
    # Update rate for all controllers
    update_rate: 50  # Hz
    
    # Controller specifications
    arm_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Arm Position Controller Configuration
arm_position_controller:
  ros__parameters:
    # Joint names
    joints:
      - joint1
      - joint2
    
    # Command interfaces
    command_interfaces:
      - position
    
    # State interfaces
    state_interfaces:
      - position
      - velocity
    
    # Trajectory execution parameters
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    
    # Trajectory tolerances
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    # Position tolerances (radians)
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.02
      joint2:
        trajectory: 0.05
        goal: 0.02
    
    # PID gains for trajectory following
    gains:
      joint1:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      joint2:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
        ff_velocity_scale: 1.0

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    # Joint names (must match URDF)
    joints:
      - joint1
      - joint2
    
    # Interfaces to publish
    interfaces:
      - position
      - velocity