# Industrial Robot Controller Configuration
# ========================================
# This configuration is designed for large industrial robots with higher
# performance requirements, more precise control, and advanced monitoring.

controller_manager:
  ros__parameters:
    update_rate: 200  # Hz - Higher update rate for industrial applications
    
    # Joint State Broadcaster - publishes joint states for visualization
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Differential Drive Controller - main velocity controller  
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    # Position Controller - for precise positioning tasks
    position_controller:
      type: position_controllers/JointGroupPositionController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    # Joint names must match those in URDF
    joints:
      - left_wheel_joint
      - right_wheel_joint
    
    # Publishing configuration
    interfaces:
      - position
      - velocity
      - effort  # Include effort for industrial monitoring
    
    # Extra joints for additional sensors
    extra_joints: []

# Differential Drive Controller Configuration
diff_drive_controller:
  ros__parameters:
    # Joint names (must match URDF)
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    # Physical robot parameters - larger industrial robot
    wheel_separation: 0.8   # meters - wider wheel base for stability
    wheels_per_side: 1      # number of wheels per side
    wheel_radius: 0.2       # meters - larger wheels for industrial use
    
    # Command interfaces
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    # Velocity and acceleration limits - higher performance
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: true
        max_velocity: 2.5        # m/s - higher max speed
        min_velocity: -2.5       # m/s
        max_acceleration: 2.0    # m/s² - higher acceleration
        min_acceleration: -2.0   # m/s²
        max_jerk: 5.0           # m/s³ - jerk limiting for smooth motion
        min_jerk: -5.0          # m/s³
    
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: true
        max_velocity: 2.0        # rad/s - higher angular velocity
        min_velocity: -2.0       # rad/s
        max_acceleration: 3.0    # rad/s² - higher angular acceleration
        min_acceleration: -3.0   # rad/s²
        max_jerk: 10.0          # rad/s³ - angular jerk limiting
        min_jerk: -10.0         # rad/s³
    
    # Publishing configuration - higher rates for industrial
    publish_rate: 100.0     # Hz - Higher state publishing rate
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.001]  # Lower covariance for better accuracy
    twist_covariance_diagonal: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.001]
    
    # TF publishing
    open_loop: false        # Always use encoder feedback for precision
    enable_odom_tf: true    # Publish odometry transform
    
    # Command timeout - shorter for safety
    cmd_vel_timeout: 0.2    # seconds - faster timeout for industrial safety
    
    # Reset odometry service
    reset_odom: false

# Position Controller Configuration (for precise positioning)
position_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    
    # Command interfaces
    interface_name: position
    
    # Position control parameters
    gains:
      left_wheel_joint:
        p: 100.0    # Proportional gain
        i: 1.0      # Integral gain  
        d: 10.0     # Derivative gain
        i_clamp: 1.0 # Integral windup limit
      right_wheel_joint:
        p: 100.0
        i: 1.0
        d: 10.0
        i_clamp: 1.0
    
    # State publishing
    state_publish_rate: 100.0  # Hz